# Generated by Django 5.1.7 on 2025-03-25 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0002_alter_user_full_name_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking', models.TextField(blank=True, null=True)),
                ('drinking', models.TextField(blank=True, null=True)),
                ('sleeping_hours', models.TextField(blank=True, null=True)),
                ('exercise_hours', models.TextField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_data', to='user_model.user')),
            ],
        ),
    ]
