# Generated by Django 5.1.7 on 2025-03-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0003_dynamicdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drinking',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='exercise_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sleeping_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='smoking',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DynamicData',
        ),
    ]
